name: Load Test Workflow

on:
  push:
    branches:
      - main

jobs:
  load_test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
          tar -xzf apache-jmeter-5.5.tgz
          rm apache-jmeter-5.5.tgz

     
      - name: Install JMeter plugins associated with thread groups
        run: apache-jmeter-5.5/bin/PluginsManagerCMD.sh install jpgc-casutg,jpgc-csh-tg,jpgc-ffw,jpgc-fifo,jpgc-function,jpgc-mt,jpgc-olap,jpgc-ordinatecontroller,jpgc-perfmon,jpgc-senseight,jpgc-synthesis

      - name: Run JMeter scripts
        run: apache-jmeter-5.5/bin/jmeter -n -t ForgeAPI_v4.jmx -l results.jtl

      - name: Generate load test report
        run: apache-jmeter-5.5/bin/jmeter -g ${{ github.workspace }}/results.jtl -o ${{ github.workspace }}/report

      - name: Print response times above 2 seconds and errors
        run: |
          awk -F',' '{if (\$2 > 2000 && NR > 1) {print "Response Time: " \$2 " ms"} else if (\$7 != "" && NR > 1) {print "Error: " \$7}}' ${{ github.workspace }}/results.jtl
